import Huiwen_Gaokao_Profile_Photo_2020.gaokao_profile_flask
Huiwen_Gaokao_Profile_Photo_2020.gaokao_profile_flask.MODULE_PATH = "Huiwen_Gaokao_Profile_Photo_2020"
blueprint = Huiwen_Gaokao_Profile_Photo_2020.gaokao_profile_flask.blueprint